import "./globals.css";
import type { Metadata } from "next";
import { sf_pro } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={sf_pro.className}>{children}</body>
    </html>
  );
}
